/** [name, location, country, city, district, category, aliases[]] */
module.exports = [
  ['Trabzon Hagia Sophia Mosque', 'Trabzon', 'Turkey', 'Trabzon', 'Merkez', 'religious', ['Ayasofya Trabzon', 'Trabzon Museum Mosque'], true, 'Ücretsiz'],
  ['Rize Ayder Plateau', 'Rize', 'Turkey', 'Rize', 'Ayder', 'nature', ['Ayder Yaylasi', 'Ayder Plateau Rize'], true],
  ['Rize Firtina Valley', 'Rize', 'Turkey', 'Rize', 'Camlıhemsin', 'nature', ['Firtina Deresi', 'Firtina Valley'], true],
  ['Mersin Maidens Castle', 'Mersin', 'Turkey', 'Mersin', 'Kizkalesi', 'landmark', ['Kizkalesi', 'Maiden Castle Mersin'], true],
  ['Konya Mevlana Museum', 'Konya', 'Turkey', 'Konya', 'Selcuklu', 'museum', ['Mevlana Museum', 'Rumi Tomb'], true, 'Ücretli'],
  ['Konya Sille Village', 'Konya', 'Turkey', 'Konya', 'Sille', 'landmark', ['Sille Konya', 'Sille Village'], true],
  ['Bursa Uludag Ski Area', 'Bursa', 'Turkey', 'Bursa', 'Uludag', 'adventure', ['Uludag Mountain', 'Uludag Bursa'], true],
  ['Bursa Cumalikizik Village', 'Bursa', 'Turkey', 'Bursa', 'Cumalikizik', 'landmark', ['Cumalikizik', 'Ottoman Village Bursa'], true],
  ['Edirne Selimiye Mosque', 'Edirne', 'Turkey', 'Edirne', 'Merkez', 'religious', ['Selimiye Camii', 'Selimiye Mosque Edirne'], true, 'Ücretsiz'],
  ['Amasya Yali Boyu Houses', 'Amasya', 'Turkey', 'Amasya', 'Yali Boyu', 'landmark', ['Amasya Ottoman Houses', 'Yali Boyu'], true],
  ['Gaziantep Zeugma Mosaic Museum', 'Gaziantep', 'Turkey', 'Gaziantep', 'Sehitkamil', 'museum', ['Zeugma Museum', 'Gaziantep Mosaic'], true, 'Ücretli'],
  ['Sanliurfa Gobekli Tepe', 'Sanliurfa', 'Turkey', 'Sanliurfa', 'Haliliye', 'landmark', ['Gobekli Tepe', 'Urfa Ancient Site'], true, 'Ücretli'],
  ['Hatay St Pierre Church', 'Hatay', 'Turkey', 'Antakya', 'Merkez', 'religious', ['St Pierre Antakya', 'Antioch Cave Church'], true],
  ['Fethiye Oludeniz Beach', 'Mugla', 'Turkey', 'Fethiye', 'Oludeniz', 'beach', ['Oludeniz Lagoon', 'Blue Lagoon Fethiye'], true],
  ['Kas Kaputas Beach', 'Antalya', 'Turkey', 'Kas', 'Kaputas', 'beach', ['Kaputas Beach', 'Kas Beach'], true, 'Ücretsiz'],
  ['Pamukkale Hierapolis', 'Denizli', 'Turkey', 'Pamukkale', 'Hierapolis', 'nature', ['Pamukkale Travertines', 'Cotton Castle'], true, 'Ücretli'],
  ['Kars Ani Ruins', 'Kars', 'Turkey', 'Kars', 'Ani', 'landmark', ['Ani Ancient City', 'City of 1001 Churches'], true, 'Ücretli'],
  ['Erzurum Oltu Stone Bridge', 'Erzurum', 'Turkey', 'Erzurum', 'Oltu', 'landmark', ['Oltu Bridge', 'Tas Kopru Oltu'], true],
  ['Akyaka Azmak River', 'Mugla', 'Turkey', 'Akyaka', 'Azmak', 'nature', ['Azmak Creek', 'Akyaka River'], true],
  ['Canakkale Troy Ancient City', 'Canakkale', 'Turkey', 'Canakkale', 'Tevfikiye', 'landmark', ['Troy Archaeological Site', 'Truva'], true, 'Ücretli'],
  ['Izmir Kordon Promenade', 'Izmir', 'Turkey', 'Izmir', 'Alsancak', 'landmark', ['Kordon Izmir', 'Izmir Waterfront'], true, 'Ücretsiz'],
  ['Antalya Termessos Ruins', 'Antalya', 'Turkey', 'Antalya', 'Termessos', 'landmark', ['Termessos Ancient City', 'Termessos Theatre'], true, 'Ücretli'],
  ['Eskisehir Odunpazari Houses', 'Eskisehir', 'Turkey', 'Eskisehir', 'Odunpazari', 'landmark', ['Odunpazari', 'Eskisehir Old Town'], true],
  ['Tunceli Munzur Valley', 'Tunceli', 'Turkey', 'Tunceli', 'Munzur', 'nature', ['Munzur Vadisi', 'Munzur National Park'], true],
  ['Gaziantep Baklava Workshop', 'Gaziantep', 'Turkey', 'Gaziantep', 'Sehitkamil', 'restaurant', ['Gaziantep Baklava', 'Baklava Tasting'], true],
  ['San Antonio River Walk', 'San Antonio', 'USA', 'San Antonio', 'Downtown', 'landmark', ['River Walk San Antonio', 'Paseo del Rio']],
  ['Austin Texas State Capitol', 'Austin', 'USA', 'Austin', 'Downtown', 'landmark', ['Texas Capitol', 'Austin Capitol']],
  ['Franklin Barbecue Austin', 'Austin', 'USA', 'Austin', 'East Austin', 'restaurant', ['Franklin BBQ', 'Austin Barbecue']],
  ['Memphis Beale Street', 'Memphis', 'USA', 'Memphis', 'Beale Street', 'nightlife', ['Beale Street Memphis', 'Blues District']],
  ['Philadelphia Independence Hall', 'Philadelphia', 'USA', 'Philadelphia', 'Old City', 'landmark', ['Independence Hall', 'Liberty Bell Area']],
  ['Pittsburgh Strip District', 'Pittsburgh', 'USA', 'Pittsburgh', 'Strip District', 'market', ['Strip District Pittsburgh', 'Pittsburgh Market']],
  ['Cleveland Rock and Roll Hall', 'Cleveland', 'USA', 'Cleveland', 'Lake Erie', 'museum', ['Rock Hall', 'Rock and Roll Hall of Fame']],
  ['Santa Fe Plaza', 'Santa Fe', 'USA', 'Santa Fe', 'Plaza', 'landmark', ['Santa Fe Historic Plaza', 'The Plaza Santa Fe']],
  ['Sedona Cathedral Rock', 'Sedona', 'USA', 'Sedona', 'Red Rock', 'nature', ['Cathedral Rock', 'Sedona Red Rocks']],
  ['Monument Valley Viewpoint', 'Monument Valley', 'USA', 'Oljato', 'Monument Valley', 'viewpoint', ['Monument Valley Navajo', 'Mittens View']],
  ['Taos Pueblo', 'Taos', 'USA', 'Taos', 'Pueblo', 'landmark', ['Taos Indian Pueblo', 'Taos Pueblo Village']],
  ['San Diego Balboa Park', 'San Diego', 'USA', 'San Diego', 'Balboa Park', 'park', ['Balboa Park San Diego', 'Balboa Gardens']],
  ['Asheville Biltmore Estate', 'Asheville', 'USA', 'Asheville', 'Biltmore', 'landmark', ['Biltmore House', 'Biltmore Estate NC'], false, 'Ücretli'],
  ['St Augustine Castillo de San Marcos', 'St Augustine', 'USA', 'St Augustine', 'Historic District', 'landmark', ['Castillo de San Marcos', 'St Augustine Fort']],
  ['Milwaukee Art Museum', 'Milwaukee', 'USA', 'Milwaukee', 'Lakefront', 'museum', ['Milwaukee Art Museum Calatrava', 'MAM Milwaukee']],
  ['Houston Space Center', 'Houston', 'USA', 'Houston', 'Clear Lake', 'museum', ['Space Center Houston', 'NASA Houston'], false, 'Ücretli'],
  ['Dallas Sixth Floor Museum', 'Dallas', 'USA', 'Dallas', 'Dealey Plaza', 'museum', ['Sixth Floor Museum', 'JFK Museum Dallas']],
  ['Atlanta Martin Luther King Site', 'Atlanta', 'USA', 'Atlanta', 'Sweet Auburn', 'landmark', ['MLK Historic Site', 'Martin Luther King Jr Park']],
  ['Phoenix Desert Botanical Garden', 'Phoenix', 'USA', 'Phoenix', 'Papago Park', 'nature', ['Desert Botanical Garden', 'Phoenix Desert Garden'], false, 'Ücretli'],
  ['Tucson Saguaro National Park', 'Tucson', 'USA', 'Tucson', 'Saguaro East', 'nature', ['Saguaro NP', 'Saguaro National Park']],
  ['Albuquerque Old Town', 'Albuquerque', 'USA', 'Albuquerque', 'Old Town', 'landmark', ['Old Town Albuquerque', 'Albuquerque Plaza']],
  ['Louisville Churchill Downs', 'Louisville', 'USA', 'Louisville', 'Churchill Downs', 'landmark', ['Churchill Downs', 'Kentucky Derby Track']],
  ['Indianapolis Motor Speedway Museum', 'Indianapolis', 'USA', 'Indianapolis', 'Speedway', 'museum', ['IMS Museum', 'Indy 500 Museum']],
  ['Richmond Carytown Market', 'Richmond', 'USA', 'Richmond', 'Carytown', 'market', ['Carytown Richmond', 'Carytown Shopping']],
  ['Charlotte NASCAR Hall of Fame', 'Charlotte', 'USA', 'Charlotte', 'Uptown', 'museum', ['NASCAR Hall of Fame', 'NASCAR Charlotte']],
  ['Salt Lake City Temple Square', 'Salt Lake City', 'USA', 'Salt Lake City', 'Temple Square', 'religious', ['Temple Square', 'Salt Lake Temple Area']],
  ['Honolulu Iolani Palace', 'Honolulu', 'USA', 'Honolulu', 'Downtown', 'landmark', ['Iolani Palace', 'Hawaii Royal Palace'], false, 'Ücretli'],
  ['Napa Valley Wine Train', 'Napa', 'USA', 'Napa', 'Wine Country', 'restaurant', ['Napa Wine Train', 'Napa Valley Dining']],
  ['New York High Line', 'New York', 'USA', 'New York', 'Chelsea', 'park', ['The High Line', 'High Line Park NYC']],
  ['Las Vegas Fremont Street', 'Las Vegas', 'USA', 'Las Vegas', 'Fremont Street', 'nightlife', ['Fremont Street Experience', 'Downtown Las Vegas']],
  ['Portland Voodoo Doughnut', 'Portland', 'USA', 'Portland', 'Old Town', 'cafe', ['Voodoo Doughnut', 'Portland Donuts']],
  ['Minneapolis Mill City Museum', 'Minneapolis', 'USA', 'Minneapolis', 'Mill District', 'museum', ['Mill City Museum', 'Minneapolis Flour Mill']],
  ['Zhangye Danxia Landform', 'Gansu', 'China', 'Zhangye', 'Danxia', 'nature', ['Zhangye Rainbow Mountains', 'Danxia Geopark']],
  ['Dunhuang Mogao Caves', 'Gansu', 'China', 'Dunhuang', 'Mogao', 'religious', ['Mogao Caves', 'Thousand Buddha Caves'], false, 'Ücretli'],
  ['Kunming Stone Forest', 'Yunnan', 'China', 'Kunming', 'Shilin', 'nature', ['Shilin Stone Forest', 'Stone Forest Kunming'], false, 'Ücretli'],
  ['Xiamen Gulangyu Island', 'Fujian', 'China', 'Xiamen', 'Gulangyu', 'landmark', ['Gulangyu', 'Piano Island Xiamen']],
  ['Tianjin Eye Ferris Wheel', 'Tianjin', 'China', 'Tianjin', 'Haihe', 'viewpoint', ['Tianjin Eye', 'Yongle Bridge Wheel']],
  ['Chongqing Hongya Cave', 'Chongqing', 'China', 'Chongqing', 'Yuzhong', 'landmark', ['Hongya Cave', 'Hongyadong']],
  ['Fenghuang Ancient Town', 'Hunan', 'China', 'Fenghuang', 'Old Town', 'landmark', ['Phoenix Ancient Town', 'Fenghuang Old Town']],
  ['Jiuzhaigou National Park', 'Sichuan', 'China', 'Jiuzhaigou', 'Valley', 'nature', ['Jiuzhaigou Valley', 'Nine Village Valley'], false, 'Ücretli'],
  ['Dali Erhai Lake', 'Yunnan', 'China', 'Dali', 'Erhai', 'nature', ['Erhai Lake', 'Dali Lake Yunnan']],
  ['Shanghai Yu Garden', 'Shanghai', 'China', 'Shanghai', 'Huangpu', 'park', ['Yu Garden', 'Yuyuan Garden Shanghai'], false, 'Ücretli'],
  ['Beijing Temple of Heaven', 'Beijing', 'China', 'Beijing', 'Dongcheng', 'religious', ['Temple of Heaven', 'Tiantan Park']],
  ['Shaolin Temple Dengfeng', 'Henan', 'China', 'Dengfeng', 'Shaolin', 'religious', ['Shaolin Temple', 'Shaolin Monastery']],
  ['Guangzhou Chen Clan Academy', 'Guangdong', 'China', 'Guangzhou', 'Liwan', 'museum', ['Chen Clan Ancestral Hall', 'Chen Jia Ci']],
  ['Hong Kong Stanley Market', 'Hong Kong', 'China', 'Hong Kong', 'Stanley', 'market', ['Stanley Market', 'Stanley Village Market']],
  ['Macau Senado Square Cafes', 'Macau', 'China', 'Macau', 'Senado Square', 'cafe', ['Senado Square', 'Largo do Senado Cafes']],
  ['Khajuraho Temples', 'Madhya Pradesh', 'India', 'Khajuraho', 'Western Group', 'religious', ['Khajuraho Group of Monuments', 'Khajuraho Temples MP']],
  ['Mysore Palace', 'Karnataka', 'India', 'Mysore', 'Amba Vilas', 'landmark', ['Mysuru Palace', 'Amba Vilas Palace'], false, 'Ücretli'],
  ['Chennai Marina Beach', 'Tamil Nadu', 'India', 'Chennai', 'Marina', 'beach', ['Marina Beach', 'Chennai Beachfront']],
  ['Munnar Tea Plantations', 'Kerala', 'India', 'Munnar', 'Tea Gardens', 'nature', ['Munnar Tea Estates', 'Kerala Tea Plantations']],
  ['Ladakh Pangong Lake', 'Ladakh', 'India', 'Leh', 'Pangong', 'nature', ['Pangong Tso', 'Pangong Lake Ladakh']],
  ['Amritsar Golden Temple', 'Punjab', 'India', 'Amritsar', 'Harmandir Sahib', 'religious', ['Harmandir Sahib', 'Golden Temple Amritsar'], false, 'Ücretsiz'],
  ['Kolkata Victoria Memorial', 'West Bengal', 'India', 'Kolkata', 'Maidan', 'museum', ['Victoria Memorial Hall', 'Victoria Memorial Kolkata'], false, 'Ücretli'],
  ['Mumbai CSMT Station', 'Maharashtra', 'India', 'Mumbai', 'Fort', 'landmark', ['Chhatrapati Shivaji Terminus', 'Victoria Terminus']],
  ['Hyderabad Charminar', 'Telangana', 'India', 'Hyderabad', 'Old City', 'religious', ['Charminar', 'Charminar Hyderabad']],
  ['Fatehpur Sikri', 'Uttar Pradesh', 'India', 'Agra', 'Fatehpur Sikri', 'landmark', ['Fatehpur Sikri Palace', 'Mughal City Sikri'], false, 'Ücretli'],
  ['Pondicherry French Quarter', 'Puducherry', 'India', 'Pondicherry', 'White Town', 'landmark', ['Pondicherry White Town', 'French Quarter Puducherry']],
  ['Coorg Abbey Falls', 'Karnataka', 'India', 'Madikeri', 'Coorg', 'nature', ['Abbey Falls Coorg', 'Coorg Waterfalls']],
  ['Shillong Laitlum Canyon', 'Meghalaya', 'India', 'Shillong', 'Laitlum', 'viewpoint', ['Laitlum Canyon', 'Laitlum Grand Canyon']],
  ['Pushkar Brahma Temple', 'Rajasthan', 'India', 'Pushkar', 'Pushkar Lake', 'religious', ['Brahma Temple Pushkar', 'Pushkar Temple']],
  ['Kochi Fort Kochi', 'Kerala', 'India', 'Kochi', 'Fort Kochi', 'landmark', ['Fort Kochi', 'Chinese Fishing Nets Kochi']],
  ['Alexandria Bibliotheca Alexandrina', 'Alexandria', 'Egypt', 'Alexandria', 'Corniche', 'museum', ['Bibliotheca Alexandrina', 'Alexandria Library']],
  ['Mozambique Island Stone Town', 'Nampula', 'Mozambique', 'Ilha de Mocambique', 'Stone Town', 'landmark', ['Ilha de Mocambique', 'Mozambique Island UNESCO']],
  ['Timbuktu Sankore Mosque', 'Timbuktu', 'Mali', 'Timbuktu', 'Sankore', 'religious', ['Sankore Mosque', 'Timbuktu Manuscripts']],
  ['Accra Jamestown Fishing Harbor', 'Accra', 'Ghana', 'Accra', 'Jamestown', 'landmark', ['Jamestown Accra', 'Accra Fishing Village']],
  ['Lesotho Sani Pass', 'Lesotho', 'Lesotho', 'Sani Top', 'Sani Pass', 'adventure', ['Sani Pass', 'Drakensberg Sani Pass']],
  ['Swakopmund Beach', 'Erongo', 'Namibia', 'Swakopmund', 'Beachfront', 'beach', ['Swakopmund', 'Namibia Atlantic Coast']],
  ['Maputo Central Train Station', 'Maputo', 'Mozambique', 'Maputo', 'Baixa', 'landmark', ['Maputo Railway Station', 'CFM Maputo']],
  ['Djibouti Lac Assal', 'Djibouti', 'Djibouti', 'Lac Assal', 'Assal', 'nature', ['Lake Assal', 'Lac Assal Salt Lake']],
  ['Madagascar Avenue of Baobabs', 'Menabe', 'Madagascar', 'Morondava', 'Baobab Alley', 'nature', ['Avenue of the Baobabs', 'Baobab Alley Madagascar']],
  ['Zimbabwe Victoria Falls Gorge', 'Matabeleland', 'Zimbabwe', 'Victoria Falls', 'Gorge', 'viewpoint', ['Victoria Falls Zimbabwe', 'Devils Cataract View']],
  ['Malawi Cape Maclear', 'Malawi', 'Malawi', 'Cape Maclear', 'Lake Malawi', 'beach', ['Cape Maclear Beach', 'Lake Malawi Beach']],
  ['Casablanca Hassan II Mosque', 'Casablanca', 'Morocco', 'Casablanca', 'Ain Diab', 'religious', ['Hassan II Mosque', 'Casablanca Mosque']],
  ['Lagos Lekki Conservation Centre', 'Lagos', 'Nigeria', 'Lagos', 'Lekki', 'nature', ['Lekki Conservation Centre', 'LCC Lagos Canopy Walk']],
  ['Ouagadougou Grand Market', 'Ouagadougou', 'Burkina Faso', 'Ouagadougou', 'Grand Market', 'market', ['Grand Marche Ouagadougou', 'Ouagadougou Market']],
  ['Addis Ababa National Museum', 'Addis Ababa', 'Ethiopia', 'Addis Ababa', 'Arat Kilo', 'museum', ['National Museum Ethiopia', 'Lucy Museum Addis']],
  ['Valparaiso Cerro Alegre', 'Valparaiso', 'Chile', 'Valparaiso', 'Cerro Alegre', 'landmark', ['Valparaiso Hills', 'Cerro Alegre Valparaiso']],
  ['Bogota Monserrate Hill', 'Bogota', 'Colombia', 'Bogota', 'Monserrate', 'viewpoint', ['Monserrate', 'Monserrate Bogota']],
  ['Machu Picchu Citadel', 'Cusco', 'Peru', 'Aguas Calientes', 'Machu Picchu', 'landmark', ['Machu Picchu', 'Lost City of the Incas'], false, 'Ücretli'],
  ['Nazca Lines Overlook', 'Ica', 'Peru', 'Nazca', 'Desert', 'landmark', ['Nazca Lines', 'Nazca Geoglyphs']],
  ['Salar de Uyuni', 'Potosi', 'Bolivia', 'Uyuni', 'Salt Flats', 'nature', ['Uyuni Salt Flats', 'Salar de Uyuni Bolivia']],
  ['La Paz Witches Market', 'La Paz', 'Bolivia', 'La Paz', 'Mercado de las Brujas', 'market', ['Mercado de las Brujas', 'Witches Market La Paz']],
  ['Colonia del Sacramento', 'Colonia', 'Uruguay', 'Colonia del Sacramento', 'Barrio Historico', 'landmark', ['Colonia Uruguay', 'Colonia Historic Quarter']],
  ['Otavalo Indigenous Market', 'Imbabura', 'Ecuador', 'Otavalo', 'Plaza de Ponchos', 'market', ['Otavalo Market', 'Plaza de Ponchos Otavalo']],
  ['Angel Falls Canaima', 'Bolivar', 'Venezuela', 'Canaima', 'Angel Falls', 'nature', ['Angel Falls', 'Salto Angel Venezuela']],
  ['Costa Rica Arenal Volcano', 'Alajuela', 'Costa Rica', 'La Fortuna', 'Arenal', 'nature', ['Arenal Volcano', 'Volcan Arenal']],
  ['Monteverde Cloud Forest', 'Puntarenas', 'Costa Rica', 'Monteverde', 'Cloud Forest', 'nature', ['Monteverde Reserve', 'Cloud Forest Costa Rica'], false, 'Ücretli'],
  ['Panama Casco Viejo', 'Panama City', 'Panama', 'Panama City', 'Casco Viejo', 'landmark', ['Casco Antiguo', 'Old Panama City']],
  ['Havana Vieja Plaza', 'Havana', 'Cuba', 'Havana', 'Old Havana', 'landmark', ['Old Havana', 'Habana Vieja Plaza']],
  ['Vinales Valley Cuba', 'Pinar del Rio', 'Cuba', 'Vinales', 'Valley', 'nature', ['Valle de Vinales', 'Vinales Mogotes']],
  ['Palenque Maya Ruins', 'Chiapas', 'Mexico', 'Palenque', 'Archaeological Zone', 'landmark', ['Palenque Ruins', 'Palenque Temple of Inscriptions']],
  ['Guanajuato Callejoneadas', 'Guanajuato', 'Mexico', 'Guanajuato', 'Centro', 'landmark', ['Guanajuato City', 'Guanajuato Tunnels']],
  ['San Miguel de Allende Parroquia', 'San Miguel de Allende', 'Mexico', 'San Miguel de Allende', 'Centro', 'religious', ['Parroquia San Miguel', 'San Miguel Church']],
  ['Rio Copacabana Beach', 'Rio de Janeiro', 'Brazil', 'Rio de Janeiro', 'Copacabana', 'beach', ['Copacabana Beach', 'Praia de Copacabana']],
  ['Salvador Acaraje Market', 'Bahia', 'Brazil', 'Salvador', 'Pelourinho', 'market', ['Acaraje Salvador', 'Baiana Food Market']],
  ['Iquitos Amazon Riverfront', 'Loreto', 'Peru', 'Iquitos', 'Amazon River', 'nature', ['Iquitos Amazon', 'Amazon River Peru']],
  ['Wroclaw Market Square', 'Wroclaw', 'Poland', 'Wroclaw', 'Rynek', 'landmark', ['Rynek Wroclaw', 'Wroclaw Old Town']],
  ['Prague Astronomical Clock', 'Prague', 'Czech Republic', 'Prague', 'Stare Mesto', 'landmark', ['Orloj Prague', 'Prague Old Town Clock']],
  ['Cesky Krumlov Castle', 'South Bohemia', 'Czech Republic', 'Cesky Krumlov', 'Castle', 'landmark', ['Cesky Krumlov', 'Krumlov Castle']],
  ['Kutna Hora Sedlec Ossuary', 'Central Bohemia', 'Czech Republic', 'Kutna Hora', 'Sedlec', 'religious', ['Bone Church Kutna Hora', 'Sedlec Ossuary']],
  ['Sofia Alexander Nevsky Cathedral', 'Sofia', 'Bulgaria', 'Sofia', 'Centrum', 'religious', ['Alexander Nevsky', 'Sofia Cathedral']],
  ['Plovdiv Old Town', 'Plovdiv', 'Bulgaria', 'Plovdiv', 'Kapana', 'landmark', ['Plovdiv Roman Theatre', 'Old Town Plovdiv']],
  ['Nessebar Old Town', 'Burgas', 'Bulgaria', 'Nessebar', 'Old Town', 'landmark', ['Nesebar', 'Nessebar UNESCO']],
  ['Veliko Tarnovo Tsarevets', 'Veliko Tarnovo', 'Bulgaria', 'Veliko Tarnovo', 'Tsarevets', 'landmark', ['Tsarevets Fortress', 'Veliko Tarnovo Fortress']],
  ['Timisoara Victory Square', 'Timisoara', 'Romania', 'Timisoara', 'Piata Victoriei', 'landmark', ['Piata Victoriei', 'Timisoara Revolution Square']],
  ['Cluj-Napoca Union Square', 'Cluj-Napoca', 'Romania', 'Cluj-Napoca', 'Piata Unirii', 'landmark', ['Piata Unirii Cluj', 'Cluj Old Town']],
  ['Novi Sad Petrovaradin Fortress', 'Novi Sad', 'Serbia', 'Novi Sad', 'Petrovaradin', 'landmark', ['Petrovaradin Fortress', 'EXIT Festival Fortress']],
  ['Skopje Old Bazaar', 'Skopje', 'North Macedonia', 'Skopje', 'Stara Carsija', 'market', ['Stara Carsija', 'Skopje Bazaar']],
  ['Durmitor National Park', 'Montenegro', 'Montenegro', 'Zabljak', 'Durmitor', 'nature', ['Durmitor NP', 'Black Lake Durmitor']],
  ['Trondheim Nidaros Cathedral', 'Trondheim', 'Norway', 'Trondheim', 'Midtbyen', 'religious', ['Nidaros Cathedral', 'Nidarosdomen']],
  ['Alesund Art Nouveau Harbor', 'More og Romsdal', 'Norway', 'Alesund', 'Harbor', 'landmark', ['Alesund Harbor', 'Jugendstil Alesund']],
  ['Tromso Arctic Cathedral', 'Tromso', 'Norway', 'Tromso', 'Tromsdalen', 'religious', ['Arctic Cathedral', 'Ishavskatedralen']],
  ['Turku Castle', 'Turku', 'Finland', 'Turku', 'Castle Hill', 'landmark', ['Turun Linna', 'Turku Castle Finland']],
  ['Kiruna Icehotel', 'Norrbotten', 'Sweden', 'Kiruna', 'Jukkasjarvi', 'adventure', ['Icehotel Sweden', 'Jukkasjarvi Ice Hotel'], false, 'Ücretli'],
  ['Abisko Northern Lights View', 'Norrbotten', 'Sweden', 'Abisko', 'National Park', 'nature', ['Abisko Aurora', 'Northern Lights Abisko']],
  ['Tallinn Telliskivi Creative City', 'Tallinn', 'Estonia', 'Tallinn', 'Telliskivi', 'landmark', ['Telliskivi', 'Telliskivi Creative City']],
  ['Riga Central Market', 'Riga', 'Latvia', 'Riga', 'Central Market', 'market', ['Riga Central Market', 'Riga Zeppelin Hangars']],
  ['Vilnius Uzupis Republic', 'Vilnius', 'Lithuania', 'Vilnius', 'Uzupis', 'landmark', ['Uzupis', 'Republic of Uzupis']],
  ['Iceland Reynisfjara Black Beach', 'South Iceland', 'Iceland', 'Vik', 'Reynisfjara', 'beach', ['Reynisfjara', 'Black Sand Beach Iceland']],
  ['Faroe Islands Saksun Village', 'Faroe Islands', 'Denmark', 'Streymoy', 'Saksun', 'nature', ['Saksun', 'Saksun Faroe Islands']],
  ['Isle of Man Peel Castle', 'Isle of Man', 'UK', 'Peel', 'Peel Castle', 'landmark', ['Peel Castle', 'Peel Isle of Man']],
  ['Tokyo Tsukiji Outer Market', 'Tokyo', 'Japan', 'Tokyo', 'Tsukiji', 'market', ['Tsukiji Outer Market', 'Tsukiji Fish Market']],
  ['Osaka Dotonbori', 'Osaka', 'Japan', 'Osaka', 'Dotonbori', 'nightlife', ['Dotonbori', 'Dotonbori Neon Osaka']],
  ['Seoul Gwangjang Market', 'Seoul', 'South Korea', 'Seoul', 'Jongno', 'market', ['Gwangjang Market', 'Seoul Street Food Market']],
  ['Hanoi Train Street', 'Hanoi', 'Vietnam', 'Hanoi', 'Old Quarter', 'landmark', ['Hanoi Train Track', 'Train Street Hanoi']],
  ['Da Nang Golden Bridge', 'Da Nang', 'Vietnam', 'Da Nang', 'Ba Na Hills', 'viewpoint', ['Golden Bridge Vietnam', 'Ba Na Hills Bridge']],
  ['Penang Gurney Drive Food', 'Penang', 'Malaysia', 'George Town', 'Gurney Drive', 'restaurant', ['Gurney Drive', 'Penang Hawker Food']],
  ['Sydney Opera House', 'Sydney', 'Australia', 'Sydney', 'Bennelong Point', 'landmark', ['Opera House Sydney', 'Sydney Opera']],
  ['Melbourne Queen Victoria Market', 'Melbourne', 'Australia', 'Melbourne', 'Queen Victoria Market', 'market', ['Queen Vic Market', 'QVM Melbourne']],
  ['Fiji Cloudbreak Surf', 'Mamanuca', 'Fiji', 'Mamanuca Islands', 'Cloudbreak', 'adventure', ['Cloudbreak Fiji', 'Fiji Surf Break']],
  ['Palawan El Nido Lagoons', 'Palawan', 'Philippines', 'El Nido', 'Bacuit Bay', 'nature', ['El Nido Lagoons', 'Big Lagoon El Nido']],
  ['Split Diocletian Palace', 'Split', 'Croatia', 'Split', 'Old Town', 'landmark', ['Diocletian Palace', 'Split Old Town']],
  ['Tbilisi Old Town Sulfur Baths', 'Tbilisi', 'Georgia', 'Tbilisi', 'Abanotubani', 'spa', ['Abanotubani', 'Tbilisi Sulfur Baths']],
  ['Yerevan Cascade Complex', 'Yerevan', 'Armenia', 'Yerevan', 'Cascade', 'viewpoint', ['Cascade Yerevan', 'Yerevan Cascade']],
];
