/** [name, location, country, city, district, category, aliases[]] */
module.exports = [
  ['Basilica Cistern', 'Sultanahmet, Istanbul', 'Turkey', 'Istanbul', 'Sultanahmet', 'landmark', ['Yerebatan', 'Basilica Cistern Istanbul']],
  ['Balat Streets', 'Fatih, Istanbul', 'Turkey', 'Istanbul', 'Balat', 'landmark', ['Balat Istanbul', 'Fener Balat']],
  ['Prince Islands', 'Adalar, Istanbul', 'Turkey', 'Istanbul', 'Buyukada', 'nature', ['Adalar', 'Princes Islands']],
  ['Aspendos Theatre', 'Serik, Antalya', 'Turkey', 'Antalya', 'Serik', 'landmark', ['Aspendos']],
  ['Mount Nemrut', 'Adiyaman', 'Turkey', 'Adiyaman', 'Kahta', 'landmark', ['Nemrut Dagi', 'Mount Nemrut']],
  ['Lake Van Akdamar', 'Van', 'Turkey', 'Van', 'Gevaş', 'religious', ['Akdamar Church', 'Van Lake']],
  ['Uzungol', 'Trabzon', 'Turkey', 'Trabzon', 'Caykara', 'nature', ['Uzungol Lake']],
  ['Alacati', 'Cesme, Izmir', 'Turkey', 'Izmir', 'Alacati', 'landmark', ['Alaçatı', 'Alacati Turkey']],
  ['Cappadocia Ihlara Valley', 'Aksaray', 'Turkey', 'Aksaray', 'Ihlara', 'nature', ['Ihlara Valley']],
  ['Hattusa', 'Corum', 'Turkey', 'Corum', 'Bogazkale', 'landmark', ['Hattusha', 'Hittite Capital']],
  ['Reichstag Berlin', 'Berlin', 'Germany', 'Berlin', 'Mitte', 'landmark', ['Reichstag']],
  ['Dresden Zwinger', 'Dresden', 'Germany', 'Dresden', 'Altstadt', 'museum', ['Zwinger Palace']],
  ['Hamburg Speicherstadt', 'Hamburg', 'Germany', 'Hamburg', 'HafenCity', 'landmark', ['Speicherstadt']],
  ['Munich Marienplatz', 'Munich', 'Germany', 'Munich', 'Altstadt', 'landmark', ['Marienplatz']],
  ['Heidelberg Castle', 'Heidelberg', 'Germany', 'Heidelberg', 'Altstadt', 'landmark', ['Heidelberger Schloss']],
  ['Lubeck Old Town', 'Lubeck', 'Germany', 'Lubeck', 'Altstadt', 'landmark', ['Lübeck']],
  ['The Hague Binnenhof', 'The Hague', 'Netherlands', 'The Hague', 'Centrum', 'landmark', ['Binnenhof']],
  ['Rotterdam Cube Houses', 'Rotterdam', 'Netherlands', 'Rotterdam', 'Blaak', 'landmark', ['Kubuswoningen']],
  ['Antwerp Central Station', 'Antwerp', 'Belgium', 'Antwerp', 'Centrum', 'landmark', ['Antwerpen']],
  ['Bruges Canals', 'Bruges', 'Belgium', 'Bruges', 'Historic Centre', 'landmark', ['Brugge']],
  ['Luxembourg Old Quarter', 'Luxembourg', 'Luxembourg', 'Luxembourg', 'Ville Haute', 'landmark', ['Luxembourg City']],
  ['Geneva Jet d Eau', 'Geneva', 'Switzerland', 'Geneva', 'Eaux-Vives', 'viewpoint', ['Jet d Eau']],
  ['Lucerne Chapel Bridge', 'Lucerne', 'Switzerland', 'Lucerne', 'Altstadt', 'landmark', ['Kapellbrucke']],
  ['Grindelwald First', 'Bern', 'Switzerland', 'Grindelwald', 'First', 'nature', ['Grindelwald']],
  ['Innsbruck Golden Roof', 'Innsbruck', 'Austria', 'Innsbruck', 'Altstadt', 'landmark', ['Goldenes Dachl']],
  ['Salzburg Fortress', 'Salzburg', 'Austria', 'Salzburg', 'Altstadt', 'landmark', ['Hohensalzburg']],
  ['Lake Como Varenna', 'Lombardy', 'Italy', 'Varenna', 'Lake Como', 'viewpoint', ['Varenna']],
  ['Verona Arena', 'Verona', 'Italy', 'Verona', 'Centro', 'landmark', ['Arena di Verona']],
  ['Bologna Towers', 'Bologna', 'Italy', 'Bologna', 'Centro', 'landmark', ['Due Torri']],
  ['Palermo Cathedral', 'Palermo', 'Italy', 'Palermo', 'Centro', 'religious', ['Cattedrale Palermo']],
  ['Valley of the Temples', 'Agrigento', 'Italy', 'Agrigento', 'Valle dei Templi', 'landmark', ['Agrigento']],
  ['Trulli of Alberobello', 'Puglia', 'Italy', 'Alberobello', 'Rione Monti', 'landmark', ['Alberobello']],
  ['Matera Sassi', 'Basilicata', 'Italy', 'Matera', 'Sassi', 'landmark', ['Sassi di Matera']],
  ['Rhodes Old Town', 'Rhodes', 'Greece', 'Rhodes', 'Medieval City', 'landmark', ['Rodos']],
  ['Corfu Old Fortress', 'Corfu', 'Greece', 'Corfu', 'Kerkyra', 'landmark', ['Kerkyra Fortress']],
  ['Zakynthos Navagio', 'Zakynthos', 'Greece', 'Zakynthos', 'Shipwreck Beach', 'beach', ['Navagio Beach']],
  ['Meteora Sunset View', 'Kalabaka', 'Greece', 'Kalabaka', 'Meteora', 'viewpoint', ['Meteora Sunset']],
  ['Chania Venetian Harbour', 'Crete', 'Greece', 'Chania', 'Old Harbour', 'landmark', ['Chania Crete']],
  ['Loire Chateau Amboise', 'Loire', 'France', 'Amboise', 'Chateau', 'landmark', ['Chateau d Amboise']],
  ['Mont Blanc View Chamonix', 'Chamonix', 'France', 'Chamonix', 'Aiguille du Midi', 'viewpoint', ['Mont Blanc']],
  ['Strasbourg Petite France', 'Strasbourg', 'France', 'Strasbourg', 'Petite France', 'landmark', ['Strasbourg']],
  ['Bordeaux Place de la Bourse', 'Bordeaux', 'France', 'Bordeaux', 'Centre', 'landmark', ['Miroir d Eau']],
  ['Lyon Vieux Lyon', 'Lyon', 'France', 'Lyon', 'Vieux Lyon', 'landmark', ['Old Lyon']],
  ['Marseille Calanques', 'Marseille', 'France', 'Marseille', 'Calanques', 'nature', ['Les Calanques']],
  ['Avignon Papal Palace', 'Avignon', 'France', 'Avignon', 'Palais des Papes', 'landmark', ['Palais des Papes']],
  ['Toledo Old City', 'Toledo', 'Spain', 'Toledo', 'Casco Historico', 'landmark', ['Toledo Spain']],
  ['Granada Albayzin', 'Granada', 'Spain', 'Granada', 'Albaicin', 'landmark', ['Albayzin']],
  ['Santiago Cathedral', 'Galicia', 'Spain', 'Santiago de Compostela', 'Centro', 'religious', ['Camino de Santiago']],
  ['Ronda Puente Nuevo', 'Malaga', 'Spain', 'Ronda', 'El Tajo', 'viewpoint', ['Puente Nuevo']],
  ['Ibiza Dalt Vila', 'Ibiza', 'Spain', 'Ibiza', 'Dalt Vila', 'landmark', ['Eivissa']],
  ['Canary Teide', 'Tenerife', 'Spain', 'Tenerife', 'Teide NP', 'nature', ['Mount Teide']],
  ['Oxford Radcliffe Camera', 'Oxford', 'UK', 'Oxford', 'City Centre', 'landmark', ['Radcliffe Camera']],
  ['Bath Roman Baths', 'Bath', 'UK', 'Bath', 'City Centre', 'museum', ['Roman Baths Bath']],
  ['York Minster', 'York', 'UK', 'York', 'City Centre', 'religious', ['York Cathedral']],
  ['Lake Windermere', 'Cumbria', 'UK', 'Windermere', 'Bowness', 'nature', ['Windermere']],
  ['Snowdonia', 'Wales', 'UK', 'Snowdonia', 'Llanberis', 'nature', ['Eryri', 'Snowdon']],
  ['Giant Causeway Visitor', 'Antrim', 'UK', 'Bushmills', 'Causeway', 'nature', ['Causeway Coast']],
  ['Skellig Michael', 'Kerry', 'Ireland', 'Kerry', 'Skellig Rocks', 'landmark', ['Skellig Islands']],
  ['Cliffs of Moher', 'Clare', 'Ireland', 'Clare', 'Liscannor', 'viewpoint', ['Moher Cliffs']],
  ['Dublin Trinity College', 'Dublin', 'Ireland', 'Dublin', 'City Centre', 'landmark', ['Book of Kells']],
  ['Lisbon Belem Tower', 'Lisbon', 'Portugal', 'Lisbon', 'Belem', 'landmark', ['Torre de Belem']],
  ['Evora Roman Temple', 'Evora', 'Portugal', 'Evora', 'Historic Centre', 'landmark', ['Temple of Diana Evora']],
  ['Douro Valley', 'Porto', 'Portugal', 'Porto', 'Pinhao', 'nature', ['Douro Wine Region']],
  ['Azores Sete Cidades', 'Sao Miguel', 'Portugal', 'Ponta Delgada', 'Sete Cidades', 'nature', ['Azores']],
  ['Warsaw Royal Castle', 'Warsaw', 'Poland', 'Warsaw', 'Old Town', 'landmark', ['Zamek Krolewski']],
  ['Gdansk Long Market', 'Gdansk', 'Poland', 'Gdansk', 'Dlugi Targ', 'landmark', ['Danzig']],
  ['Auschwitz Memorial', 'Oswiecim', 'Poland', 'Oswiecim', 'Brzezinka', 'museum', ['Auschwitz-Birkenau']],
  ['Bratislava Castle', 'Bratislava', 'Slovakia', 'Bratislava', 'Old Town', 'landmark', ['Bratislava Hrad']],
  ['Budapest Fishermans Bastion', 'Budapest', 'Hungary', 'Budapest', 'Buda', 'viewpoint', ['Halaszbastya']],
  ['Lake Balaton Tihany', 'Balaton', 'Hungary', 'Tihany', 'Abbey', 'nature', ['Balaton']],
  ['Zagreb Upper Town', 'Zagreb', 'Croatia', 'Zagreb', 'Gornji Grad', 'landmark', ['Zagreb Cathedral area']],
  ['Hvar Fortica', 'Hvar', 'Croatia', 'Hvar', 'Stari Grad', 'viewpoint', ['Hvar Island']],
  ['Sibenik Cathedral', 'Sibenik', 'Croatia', 'Sibenik', 'Old Town', 'religious', ['St James Cathedral']],
  ['Belgrade Kalemegdan', 'Belgrade', 'Serbia', 'Belgrade', 'Kalemegdan', 'park', ['Kalemegdan Park']],
  ['Sarajevo Bascarsija', 'Sarajevo', 'Bosnia', 'Sarajevo', 'Bascarsija', 'market', ['Bashcarsiya']],
  ['Prizren Old Bridge', 'Prizren', 'Kosovo', 'Prizren', 'Old Town', 'landmark', ['Prizren Bridge']],
  ['Tirana Skanderbeg Square', 'Tirana', 'Albania', 'Tirana', 'Centrum', 'landmark', ['Skanderbeg']],
  ['Ohrid Lake', 'Ohrid', 'North Macedonia', 'Ohrid', 'Old Town', 'nature', ['Lake Ohrid']],
  ['Rila Monastery', 'Rila', 'Bulgaria', 'Rila', 'Monastery', 'religious', ['Rilski Manastir']],
  ['Bucharest Old Town', 'Bucharest', 'Romania', 'Bucharest', 'Lipscani', 'landmark', ['Lipscani']],
  ['Transylvania Bran Castle', 'Brasov', 'Romania', 'Brasov', 'Bran', 'landmark', ['Bran Castle', 'Dracula Castle']],
  ['Sighisoara Citadel', 'Mures', 'Romania', 'Sighisoara', 'Citadel', 'landmark', ['Sighisoara']],
  ['Kyiv Pechersk Lavra', 'Kyiv', 'Ukraine', 'Kyiv', 'Pechersk', 'religious', ['Kiev Lavra', 'Kyiv']],
  ['Odessa Potemkin Stairs', 'Odessa', 'Ukraine', 'Odessa', 'Primorsky', 'landmark', ['Potemkin Steps']],
  ['Minsk Independence Square', 'Minsk', 'Belarus', 'Minsk', 'Centrum', 'landmark', ['Minsk']],
  ['Tallinn Toompea', 'Tallinn', 'Estonia', 'Tallinn', 'Toompea', 'landmark', ['Toompea Hill']],
  ['Riga Art Nouveau', 'Riga', 'Latvia', 'Riga', 'Alberta iela', 'landmark', ['Art Nouveau Riga']],
  ['Vilnius Old Town', 'Vilnius', 'Lithuania', 'Vilnius', 'Senamiestis', 'landmark', ['Vilnius']],
  ['Helsinki Senate Square', 'Helsinki', 'Finland', 'Helsinki', 'Senate Square', 'landmark', ['Helsinki Cathedral area']],
  ['Lapland Rovaniemi', 'Rovaniemi', 'Finland', 'Rovaniemi', 'Arctic Circle', 'nature', ['Santa Claus Village']],
  ['Stockholm City Hall', 'Stockholm', 'Sweden', 'Stockholm', 'Kungsholmen', 'landmark', ['Stadshuset']],
  ['Gothenburg Haga', 'Gothenburg', 'Sweden', 'Gothenburg', 'Haga', 'landmark', ['Haga district']],
  ['Oslo Opera House', 'Oslo', 'Norway', 'Oslo', 'Bjervika', 'landmark', ['Oslo Opera']],
  ['Bergen Bryggen', 'Bergen', 'Norway', 'Bergen', 'Bryggen', 'landmark', ['Bryggen Wharf']],
  ['Copenhagen Tivoli', 'Copenhagen', 'Denmark', 'Copenhagen', 'Vesterbro', 'park', ['Tivoli Gardens']],
  ['Aarhus ARoS', 'Aarhus', 'Denmark', 'Aarhus', 'Centrum', 'museum', ['ARoS Museum']],
  ['Reykjavik Harpa', 'Reykjavik', 'Iceland', 'Reykjavik', 'Harpa', 'landmark', ['Harpa Concert Hall']],
  ['Jokulsarlon Glacier Lagoon', 'Hofn', 'Iceland', 'Hofn', 'Jokulsarlon', 'nature', ['Glacier Lagoon']],
  ['Akureyri', 'North Iceland', 'Iceland', 'Akureyri', 'Centrum', 'landmark', ['Akureyri Town']],
  ['St Petersburg Hermitage', 'St Petersburg', 'Russia', 'St Petersburg', 'Palace Embankment', 'museum', ['Hermitage Museum']],
  ['Kazan Kremlin', 'Kazan', 'Russia', 'Kazan', 'Kremlin', 'landmark', ['Kazan Kremlin']],
  ['Sochi Rosa Khutor', 'Sochi', 'Russia', 'Sochi', 'Rosa Khutor', 'adventure', ['Rosa Khutor']],
  ['Vladivostok Golden Bridge', 'Vladivostok', 'Russia', 'Vladivostok', 'Russky Island', 'landmark', ['Zolotoy Rog']],
  ['Red Square St Basil', 'Moscow', 'Russia', 'Moscow', 'Red Square', 'religious', ['Saint Basil Cathedral']],
  ['Petra Treasury Night', 'Petra', 'Jordan', 'Petra', 'Siq', 'landmark', ['Al-Khazneh']],
  ['Amman Citadel', 'Amman', 'Jordan', 'Amman', 'Jabal al-Qalaa', 'landmark', ['Amman Citadel']],
  ['Jerash Roman City', 'Jerash', 'Jordan', 'Jerash', 'Archaeological Site', 'landmark', ['Gerasa']],
  ['Baalbek Temples', 'Baalbek', 'Lebanon', 'Baalbek', 'Heliopolis', 'landmark', ['Baalbek Ruins']],
  ['Byblos Old Port', 'Byblos', 'Lebanon', 'Byblos', 'Old Souk', 'landmark', ['Jbeil']],
  ['Tel Aviv Carmel Market', 'Tel Aviv', 'Israel', 'Tel Aviv', 'Carmel Market', 'market', ['Shuk HaCarmel']],
  ['Masada Fortress', 'Dead Sea', 'Israel', 'Masada', 'Fortress', 'landmark', ['Masada National Park']],
  ['Doha Souq Waqif', 'Doha', 'Qatar', 'Doha', 'Souq Waqif', 'market', ['Souq Waqif']],
  ['Kuwait Grand Mosque', 'Kuwait City', 'Kuwait', 'Kuwait City', 'Grand Mosque', 'religious', ['Grand Mosque Kuwait']],
  ['Riyadh Kingdom Centre', 'Riyadh', 'Saudi Arabia', 'Riyadh', 'Olaya', 'viewpoint', ['Kingdom Centre']],
  ['AlUla Hegra', 'AlUla', 'Saudi Arabia', 'AlUla', 'Hegra', 'landmark', ['Madain Saleh', 'Hegra']],
  ['Muscat Mutrah Souq', 'Muscat', 'Oman', 'Muscat', 'Mutrah', 'market', ['Muttrah Souq']],
  ['Nizwa Fort', 'Nizwa', 'Oman', 'Nizwa', 'Fort', 'landmark', ['Nizwa Fort Oman']],
  ['Dubai Old Creek', 'Dubai', 'UAE', 'Dubai', 'Deira', 'landmark', ['Dubai Creek', 'Abra']],
  ['Abu Dhabi Louvre', 'Abu Dhabi', 'UAE', 'Abu Dhabi', 'Saadiyat', 'museum', ['Louvre Abu Dhabi']],
  ['Sharjah Heritage Area', 'Sharjah', 'UAE', 'Sharjah', 'Heritage', 'landmark', ['Sharjah']],
  ['Isfahan Naqsh-e Jahan', 'Isfahan', 'Iran', 'Isfahan', 'Imam Square', 'landmark', ['Naqsh-e Jahan Square']],
  ['Persepolis', 'Shiraz', 'Iran', 'Shiraz', 'Marvdasht', 'landmark', ['Takht-e Jamshid']],
  ['Yazd Old City', 'Yazd', 'Iran', 'Yazd', 'Historic City', 'landmark', ['Yazd Windcatchers']],
  ['Kashgar Sunday Bazaar', 'Kashgar', 'China', 'Kashgar', 'Old City', 'market', ['Kashgar Bazaar']],
  ['Potala Palace View', 'Lhasa', 'China', 'Lhasa', 'Potala', 'landmark', ['Potala']],
  ['Leshan Giant Buddha', 'Sichuan', 'China', 'Leshan', 'Lingyun', 'religious', ['Leshan Buddha']],
  ['Huangshan Yellow Mountain', 'Anhui', 'China', 'Huangshan', 'Yellow Mountain', 'nature', ['Huangshan']],
  ['Li River Guilin', 'Guangxi', 'China', 'Guilin', 'Yangshuo', 'nature', ['Yangshuo', 'Li River']],
  ['West Lake Hangzhou', 'Zhejiang', 'China', 'Hangzhou', 'West Lake', 'park', ['Xihu', 'West Lake']],
  ['Suzhou Gardens', 'Jiangsu', 'China', 'Suzhou', 'Humble Garden', 'park', ['Suzhou Classical Gardens']],
  ['Nanjing City Wall', 'Jiangsu', 'China', 'Nanjing', 'Zhonghua Gate', 'landmark', ['Nanjing Wall']],
  ['Chengdu Panda Base', 'Sichuan', 'China', 'Chengdu', 'Panda Base', 'nature', ['Giant Panda']],
  ['Harbin Ice Festival', 'Heilongjiang', 'China', 'Harbin', 'Ice City', 'landmark', ['Harbin Ice and Snow']],
  ['Xian City Wall', 'Shaanxi', 'China', "Xi'an", 'City Wall', 'landmark', ['Xian Wall', 'Xi An']],
  ['Pingyao Ancient City', 'Shanxi', 'China', 'Pingyao', 'Ancient City', 'landmark', ['Pingyao']],
  ['Hong Kong Victoria Harbour Walk', 'Hong Kong', 'China', 'Hong Kong', 'Tsim Sha Tsui', 'viewpoint', ['Victoria Harbour']],
  ['Macau Ruins of St Paul', 'Macau', 'China', 'Macau', 'Senado Square', 'landmark', ['Ruins of St Pauls']],
  ['Himeji Castle', 'Hyogo', 'Japan', 'Himeji', 'Shiro', 'landmark', ['White Heron Castle']],
  ['Miyajima Itsukushima', 'Hiroshima', 'Japan', 'Hatsukaichi', 'Miyajima', 'religious', ['Itsukushima Shrine']],
  ['Kanazawa Samurai District', 'Ishikawa', 'Japan', 'Kanazawa', 'Nagamachi', 'landmark', ['Nagamachi Samurai']],
  ['Takayama Old Town', 'Gifu', 'Japan', 'Takayama', 'Sanmachi', 'landmark', ['Takayama']],
  ['Hakone Open Air Museum', 'Kanagawa', 'Japan', 'Hakone', 'Open Air', 'museum', ['Hakone']],
  ['Nagasaki Peace Park', 'Nagasaki', 'Japan', 'Nagasaki', 'Peace Park', 'park', ['Nagasaki Peace Memorial']],
  ['Sapporo Odori Park', 'Hokkaido', 'Japan', 'Sapporo', 'Odori', 'park', ['Sapporo Snow Festival area']],
  ['Okinawa Shurijo Castle', 'Okinawa', 'Japan', 'Naha', 'Shurijo', 'landmark', ['Shuri Castle']],
  ['Busan Gamcheon', 'Busan', 'South Korea', 'Busan', 'Gamcheon', 'landmark', ['Gamcheon Culture Village']],
  ['Andong Hahoe Village', 'Gyeongsang', 'South Korea', 'Andong', 'Hahoe', 'landmark', ['Hahoe Folk Village']],
  ['Suwon Hwaseong Fortress', 'Gyeonggi', 'South Korea', 'Suwon', 'Hwaseong', 'landmark', ['Hwaseong Fortress']],
  ['Incheon Chinatown', 'Incheon', 'South Korea', 'Incheon', 'Chinatown', 'landmark', ['Incheon Chinatown']],
  ['Tainan Chihkan Tower', 'Tainan', 'Taiwan', 'Tainan', 'West Central', 'landmark', ['Fort Provintia']],
  ['Sun Moon Lake', 'Nantou', 'Taiwan', 'Nantou', 'Sun Moon Lake', 'nature', ['Sun Moon Lake Taiwan']],
  ['Taroko Gorge', 'Hualien', 'Taiwan', 'Hualien', 'Taroko', 'nature', ['Taroko National Park']],
  ['Penang George Town', 'Penang', 'Malaysia', 'George Town', 'UNESCO', 'landmark', ['George Town Penang']],
  ['Langkawi Sky Bridge', 'Langkawi', 'Malaysia', 'Langkawi', 'Sky Bridge', 'viewpoint', ['Langkawi']],
  ['Malacca Jonker Street', 'Malacca', 'Malaysia', 'Malacca', 'Jonker', 'market', ['Melaka Jonker']],
  ['Kuala Lumpur Batu Caves', 'Selangor', 'Malaysia', 'Kuala Lumpur', 'Batu Caves', 'religious', ['Batu Caves Steps']],
  ['Jakarta Old Town', 'Jakarta', 'Indonesia', 'Jakarta', 'Kota Tua', 'landmark', ['Kota Tua Jakarta']],
  ['Yogyakarta Prambanan', 'Yogyakarta', 'Indonesia', 'Yogyakarta', 'Prambanan', 'religious', ['Prambanan Temple']],
  ['Ubud Rice Terraces', 'Bali', 'Indonesia', 'Ubud', 'Tegallalang', 'nature', ['Tegallalang Rice Terrace']],
  ['Lombok Mount Rinjani', 'Lombok', 'Indonesia', 'Lombok', 'Sembalun', 'adventure', ['Mount Rinjani']],
  ['Flores Kelimutu', 'Flores', 'Indonesia', 'Moni', 'Kelimutu', 'nature', ['Kelimutu Lakes']],
  ['Chiang Rai White Temple', 'Chiang Rai', 'Thailand', 'Chiang Rai', 'Wat Rong Khun', 'religious', ['White Temple Thailand']],
  ['Ayutthaya Historical Park', 'Ayutthaya', 'Thailand', 'Ayutthaya', 'Historical Park', 'landmark', ['Ayutthaya Ruins']],
  ['Koh Samui Big Buddha', 'Koh Samui', 'Thailand', 'Koh Samui', 'Big Buddha Beach', 'religious', ['Wat Phra Yai']],
  ['Pattaya Sanctuary of Truth', 'Pattaya', 'Thailand', 'Pattaya', 'Wong Amat', 'religious', ['Sanctuary of Truth']],
  ['Luang Prabang Kuang Si', 'Luang Prabang', 'Laos', 'Luang Prabang', 'Kuang Si', 'nature', ['Kuang Si Falls']],
  ['Vientiane Patuxai', 'Vientiane', 'Laos', 'Vientiane', 'Patuxai', 'landmark', ['Victory Gate Laos']],
  ['Siem Reap Pub Street Area', 'Siem Reap', 'Cambodia', 'Siem Reap', 'Old Market', 'nightlife', ['Pub Street']],
  ['Phnom Penh Royal Palace', 'Phnom Penh', 'Cambodia', 'Phnom Penh', 'Riverside', 'landmark', ['Royal Palace Cambodia']],
  ['Ho Chi Minh War Remnants', 'Ho Chi Minh', 'Vietnam', 'Ho Chi Minh City', 'District 3', 'museum', ['War Remnants Museum']],
  ['Hue Imperial City', 'Hue', 'Vietnam', 'Hue', 'Citadel', 'landmark', ['Hue Citadel']],
  ['Sapa Rice Terraces', 'Lao Cai', 'Vietnam', 'Sapa', 'Muong Hoa', 'nature', ['Sapa Vietnam']],
  ['Mandalay U Bein Bridge', 'Mandalay', 'Myanmar', 'Amarapura', 'U Bein', 'landmark', ['U Bein Bridge']],
  ['Inle Lake', 'Shan', 'Myanmar', 'Nyaung Shwe', 'Inle Lake', 'nature', ['Inle Lake Myanmar']],
  ['Kathmandu Durbar Square', 'Kathmandu', 'Nepal', 'Kathmandu', 'Durbar Square', 'landmark', ['Kathmandu Durbar']],
  ['Pokhara Phewa Lake', 'Pokhara', 'Nepal', 'Pokhara', 'Lakeside', 'nature', ['Phewa Lake']],
  ['Chitwan National Park', 'Chitwan', 'Nepal', 'Chitwan', 'Sauraha', 'nature', ['Chitwan Safari']],
  ['Thimphu Buddha Dordenma', 'Thimphu', 'Bhutan', 'Thimphu', 'Kuensel Phodrang', 'religious', ['Great Buddha Dordenma']],
  ['Punakha Dzong', 'Punakha', 'Bhutan', 'Punakha', 'Dzong', 'religious', ['Punakha Dzong Bhutan']],
  ['Dhaka Old Dhaka', 'Dhaka', 'Bangladesh', 'Dhaka', 'Old Dhaka', 'landmark', ['Old Dhaka']],
  ['Sundarbans', 'Khulna', 'Bangladesh', 'Khulna', 'Sundarbans', 'nature', ['Sundarbans Mangrove']],
  ['Jaipur Hawa Mahal', 'Jaipur', 'India', 'Jaipur', 'Pink City', 'landmark', ['Hawa Mahal']],
  ['Udaipur Lake Palace View', 'Udaipur', 'India', 'Udaipur', 'Lake Pichola', 'viewpoint', ['Lake Pichola']],
  ['Jodhpur Mehrangarh', 'Jodhpur', 'India', 'Jodhpur', 'Blue City', 'landmark', ['Mehrangarh Fort']],
  ['Rishikesh Ganges', 'Uttarakhand', 'India', 'Rishikesh', 'Laxman Jhula', 'religious', ['Rishikesh Yoga']],
  ['Kerala Backwaters Alleppey', 'Kerala', 'India', 'Alleppey', 'Backwaters', 'nature', ['Alleppey Houseboat']],
  ['Hampi Ruins', 'Karnataka', 'India', 'Hampi', 'Bazaar', 'landmark', ['Hampi Vijayanagara']],
  ['Goa Old Goa Churches', 'Goa', 'India', 'Old Goa', 'Basilica', 'religious', ['Basilica of Bom Jesus']],
  ['Darjeeling Toy Train', 'West Bengal', 'India', 'Darjeeling', 'Ghoom', 'adventure', ['Darjeeling Himalayan Railway']],
  ['Colombo Galle Face', 'Colombo', 'Sri Lanka', 'Colombo', 'Galle Face Green', 'landmark', ['Galle Face']],
  ['Ella Nine Arch Bridge', 'Ella', 'Sri Lanka', 'Ella', 'Demodara', 'landmark', ['Nine Arch Bridge']],
  ['Yala National Park', 'Yala', 'Sri Lanka', 'Yala', 'Safari', 'nature', ['Yala Safari']],
  ['Maldives Male Friday Mosque', 'Male', 'Maldives', 'Male', 'Hukuru Miskiy', 'religious', ['Hukuru Miskiy']],
  ['Seychelles Anse Source d Argent', 'La Digue', 'Seychelles', 'La Digue', 'Anse Source', 'beach', ['Anse Source d Argent']],
  ['Mauritius Chamarel', 'Chamarel', 'Mauritius', 'Chamarel', 'Seven Coloured Earth', 'nature', ['Seven Coloured Earths']],
  ['Victoria Falls Bridge', 'Livingstone', 'Zambia', 'Livingstone', 'Victoria Falls', 'viewpoint', ['Victoria Falls Bridge']],
  ['Okavango Delta', 'Botswana', 'Botswana', 'Maun', 'Okavango', 'nature', ['Okavango Delta']],
  ['Etosha National Park', 'Namibia', 'Namibia', 'Etosha', 'Safari', 'nature', ['Etosha NP']],
  ['Sossusvlei Dunes', 'Namib Desert', 'Namibia', 'Sesriem', 'Sossusvlei', 'nature', ['Deadvlei', 'Sossusvlei']],
  ['Cape Point', 'Cape Town', 'South Africa', 'Cape Town', 'Cape Point', 'viewpoint', ['Cape of Good Hope']],
  ['Kruger National Park', 'Mpumalanga', 'South Africa', 'Kruger', 'Safari', 'nature', ['Kruger Safari']],
  ['Drakensberg Amphitheatre', 'KwaZulu-Natal', 'South Africa', 'Drakensberg', 'Royal Natal', 'nature', ['Drakensberg']],
  ['Fez Medina', 'Fez', 'Morocco', 'Fez', 'Fes el-Bali', 'market', ['Fes Medina']],
  ['Essaouira Ramparts', 'Essaouira', 'Morocco', 'Essaouira', 'Medina', 'landmark', ['Essaouira']],
  ['Atlas Mountains Imlil', 'Imlil', 'Morocco', 'Imlil', 'Atlas', 'nature', ['Imlil Morocco']],
  ['Tunis Medina', 'Tunis', 'Tunisia', 'Tunis', 'Medina', 'market', ['Tunis Medina']],
  ['Carthage Ruins', 'Carthage', 'Tunisia', 'Carthage', 'Archaeological Site', 'landmark', ['Carthage Tunisia']],
  ['Dakar Goree Island', 'Dakar', 'Senegal', 'Dakar', 'Goree', 'landmark', ['Goree Island']],
  ['Ghana Cape Coast Castle', 'Cape Coast', 'Ghana', 'Cape Coast', 'Castle', 'museum', ['Cape Coast Castle']],
  ['Lalibela Bet Giyorgis', 'Lalibela', 'Ethiopia', 'Lalibela', 'Rock Church', 'religious', ['Church of Saint George']],
  ['Simien Mountains', 'Gondar', 'Ethiopia', 'Debark', 'Simien', 'nature', ['Simien Mountains NP']],
  ['Nairobi National Park', 'Nairobi', 'Kenya', 'Nairobi', 'Safari', 'nature', ['Nairobi NP']],
  ['Maasai Mara', 'Narok', 'Kenya', 'Narok', 'Mara', 'nature', ['Masai Mara']],
  ['Diani Beach', 'Kwale', 'Kenya', 'Diani', 'Beach', 'beach', ['Diani Beach Kenya']],
  ['Ngorongoro Crater', 'Arusha', 'Tanzania', 'Ngorongoro', 'Crater', 'nature', ['Ngorongoro Crater']],
  ['Kilimanjaro Marangu Gate', 'Kilimanjaro', 'Tanzania', 'Moshi', 'Marangu', 'adventure', ['Mount Kilimanjaro']],
  ['Stone Town Zanzibar', 'Zanzibar', 'Tanzania', 'Zanzibar', 'Stone Town', 'landmark', ['Zanzibar Stone Town']],
  ['Rwanda Volcanoes NP', 'Musanze', 'Rwanda', 'Musanze', 'Volcanoes', 'nature', ['Volcanoes National Park']],
  ['Kigali Genocide Memorial', 'Kigali', 'Rwanda', 'Kigali', 'Gisozi', 'museum', ['Kigali Memorial']],
  ['Bwindi Impenetrable Forest', 'Uganda', 'Uganda', 'Bwindi', 'Gorilla Trek', 'nature', ['Bwindi Gorillas']],
  ['Murchison Falls', 'Uganda', 'Uganda', 'Murchison', 'Falls', 'nature', ['Murchison Falls NP']],
  ['Cairo Egyptian Museum', 'Cairo', 'Egypt', 'Cairo', 'Tahrir', 'museum', ['Egyptian Museum Cairo']],
  ['Karnak Temple', 'Luxor', 'Egypt', 'Luxor', 'Karnak', 'religious', ['Karnak Temple Complex']],
  ['Aswan Philae Temple', 'Aswan', 'Egypt', 'Aswan', 'Agilkia', 'religious', ['Philae Temple']],
  ['White Desert', 'Farafra', 'Egypt', 'Farafra', 'White Desert', 'nature', ['Sahara White Desert']],
  ['Dubai Desert Safari', 'Dubai', 'UAE', 'Dubai', 'Desert', 'adventure', ['Dubai Desert']],
  ['Almaty Big Almaty Lake', 'Almaty', 'Kazakhstan', 'Almaty', 'Big Almaty', 'nature', ['Big Almaty Lake']],
  ['Bishkek Ala Archa', 'Bishkek', 'Kyrgyzstan', 'Bishkek', 'Ala Archa', 'nature', ['Ala Archa NP']],
  ['Tashkent Metro Art', 'Tashkent', 'Uzbekistan', 'Tashkent', 'Metro', 'landmark', ['Tashkent Metro']],
  ['Khiva Itchan Kala', 'Khiva', 'Uzbekistan', 'Khiva', 'Itchan Kala', 'landmark', ['Ichan Kala']],
  ['Bukhara Po-i-Kalyan', 'Bukhara', 'Uzbekistan', 'Bukhara', 'Po-i-Kalyan', 'religious', ['Kalyan Minaret']],
  ['Ashgabat White Marble', 'Ashgabat', 'Turkmenistan', 'Ashgabat', 'Centrum', 'landmark', ['Ashgabat']],
  ['Darvaza Gas Crater', 'Karakum', 'Turkmenistan', 'Darvaza', 'Gas Crater', 'viewpoint', ['Door to Hell']],
  ['Ulaanbaatar Gandan', 'Ulaanbaatar', 'Mongolia', 'Ulaanbaatar', 'Gandan', 'religious', ['Gandan Monastery']],
  ['Gobi Khongoryn Els', 'Gobi', 'Mongolia', 'Gobi', 'Khongoryn Els', 'nature', ['Singing Dunes Gobi']],
  ['Lake Baikal Olkhon', 'Irkutsk', 'Russia', 'Olkhon', 'Khuzhir', 'nature', ['Olkhon Island']],
  ['Kamchatka Valley of Geysers', 'Kamchatka', 'Russia', 'Petropavlovsk', 'Geysers', 'nature', ['Valley of Geysers']],
  ['Vladivostok Russky Bridge', 'Vladivostok', 'Russia', 'Vladivostok', 'Russky Island', 'landmark', ['Russky Bridge']],
  ['Golden Circle Thingvellir', 'Iceland', 'Iceland', 'Thingvellir', 'National Park', 'nature', ['Thingvellir']],
  ['Snæfellsnes Kirkjufell', 'Iceland', 'Iceland', 'Grundarfjordur', 'Kirkjufell', 'viewpoint', ['Kirkjufell Mountain']],
  ['Faroe Islands Gasadalur', 'Faroe Islands', 'Denmark', 'Vagar', 'Gasadalur', 'viewpoint', ['Mulafossur Waterfall']],
  ['Lofoten Reine', 'Lofoten', 'Norway', 'Reine', 'Reinebringen', 'viewpoint', ['Reine Lofoten']],
  ['Preikestolen', 'Rogaland', 'Norway', 'Stavanger', 'Preikestolen', 'adventure', ['Pulpit Rock']],
  ['Geirangerfjord', 'More og Romsdal', 'Norway', 'Geiranger', 'Fjord', 'nature', ['Geiranger Fjord']],
  ['Stockholm Archipelago', 'Stockholm', 'Sweden', 'Stockholm', 'Archipelago', 'nature', ['Stockholm Archipelago']],
  ['Visby Medieval Walls', 'Gotland', 'Sweden', 'Visby', 'Medieval City', 'landmark', ['Visby Sweden']],
  ['Copenhagen Nyhavn Harbor', 'Copenhagen', 'Denmark', 'Copenhagen', 'Nyhavn', 'landmark', ['Nyhavn Copenhagen']],
  ['Legoland Billund', 'Billund', 'Denmark', 'Billund', 'Legoland', 'landmark', ['Legoland Denmark']],
  ['Brussels Atomium', 'Brussels', 'Belgium', 'Brussels', 'Heysel', 'landmark', ['Atomium']],
  ['Ghent Graslei', 'Ghent', 'Belgium', 'Ghent', 'Graslei', 'landmark', ['Gent Graslei']],
  ['Maastricht Vrijthof', 'Maastricht', 'Netherlands', 'Maastricht', 'Vrijthof', 'landmark', ['Maastricht']],
  ['Utrecht Dom Tower', 'Utrecht', 'Netherlands', 'Utrecht', 'Dom', 'landmark', ['Domtoren']],
  ['Edinburgh Royal Mile', 'Edinburgh', 'UK', 'Edinburgh', 'Royal Mile', 'landmark', ['Royal Mile']],
  ['Isle of Skye Fairy Pools', 'Skye', 'UK', 'Isle of Skye', 'Fairy Pools', 'nature', ['Fairy Pools Skye']],
  ['Cornwall St Michaels Mount', 'Cornwall', 'UK', 'Marazion', 'St Michaels Mount', 'landmark', ['St Michaels Mount']],
  ['Lake Como Bellagio Promenade', 'Bellagio', 'Italy', 'Bellagio', 'Lakeside', 'viewpoint', ['Bellagio Promenade']],
  ['Porto Douro Ribeira', 'Porto', 'Portugal', 'Porto', 'Ribeira', 'landmark', ['Ribeira Porto']],
  ['Seville Plaza de Espana', 'Seville', 'Spain', 'Seville', 'Maria Luisa', 'landmark', ['Plaza de Espana']],
  ['Valencia City of Arts', 'Valencia', 'Spain', 'Valencia', 'Ciudad de las Artes', 'museum', ['City of Arts and Sciences']],
  ['Biarritz Coast', 'Biarritz', 'France', 'Biarritz', 'Grande Plage', 'beach', ['Biarritz']],
  ['Annecy Lake', 'Annecy', 'France', 'Annecy', 'Old Town', 'nature', ['Lake Annecy']],
  ['Dolomites Seceda', 'South Tyrol', 'Italy', 'Ortisei', 'Seceda', 'nature', ['Seceda Dolomites']],
  ['Lake Bled Island Church', 'Bled', 'Slovenia', 'Bled', 'Island', 'religious', ['Bled Island']],
  ['Mostar Stari Most', 'Mostar', 'Bosnia', 'Mostar', 'Stari Most', 'landmark', ['Stari Most Bridge']],
  ['Kotor Bay View', 'Kotor', 'Montenegro', 'Kotor', 'Bay', 'viewpoint', ['Bay of Kotor']],
  ['Santorini Oia Castle', 'Santorini', 'Greece', 'Oia', 'Castle Ruins', 'viewpoint', ['Oia Castle']],
  ['Meteora Varlaam', 'Meteora', 'Greece', 'Kalabaka', 'Varlaam', 'religious', ['Varlaam Monastery']],
  ['Ephesus Library of Celsus', 'Selcuk', 'Turkey', 'Selcuk', 'Ephesus', 'landmark', ['Library of Celsus']],
  ['Cappadocia Uchisar Castle', 'Uchisar', 'Turkey', 'Nevsehir', 'Uchisar', 'viewpoint', ['Uchisar Castle']],
  ['Antalya Duden Waterfalls', 'Antalya', 'Turkey', 'Antalya', 'Duden', 'nature', ['Duden Waterfalls']],
  ['Bursa Green Mosque', 'Bursa', 'Turkey', 'Bursa', 'Yesil', 'religious', ['Green Mosque Bursa']],
  ['Trabzon Sumela Trail', 'Trabzon', 'Turkey', 'Trabzon', 'Maçka', 'adventure', ['Sumela Trail']],
  ['Mount Ararat View', 'Agri', 'Turkey', 'Dogubayazit', 'Ararat', 'viewpoint', ['Mount Ararat']],
  ['Lake Salda', 'Burdur', 'Turkey', 'Burdur', 'Salda', 'nature', ['Salda Lake Turkey Maldives']],
  ['Grand Canyon South Rim', 'Arizona', 'USA', 'Grand Canyon', 'South Rim', 'viewpoint', ['Grand Canyon South']],
  ['Zion National Park', 'Utah', 'USA', 'Springdale', 'Zion', 'nature', ['Zion NP']],
  ['Arches Delicate Arch', 'Utah', 'USA', 'Moab', 'Arches', 'nature', ['Delicate Arch']],
  ['Bryce Canyon Amphitheater', 'Utah', 'USA', 'Bryce', 'Amphitheater', 'nature', ['Bryce Canyon']],
  ['Miami South Beach', 'Miami', 'USA', 'Miami Beach', 'South Beach', 'beach', ['South Beach Miami']],
  ['New Orleans French Quarter', 'New Orleans', 'USA', 'New Orleans', 'French Quarter', 'landmark', ['French Quarter NOLA']],
  ['Chicago Millennium Park', 'Chicago', 'USA', 'Chicago', 'Loop', 'park', ['Cloud Gate', 'The Bean']],
  ['Seattle Space Needle', 'Seattle', 'USA', 'Seattle', 'Queen Anne', 'viewpoint', ['Space Needle']],
  ['Portland Japanese Garden', 'Portland', 'USA', 'Portland', 'Washington Park', 'park', ['Portland Japanese Garden']],
  ['Boston Freedom Trail', 'Boston', 'USA', 'Boston', 'Freedom Trail', 'landmark', ['Freedom Trail Boston']],
  ['Washington DC Lincoln Memorial', 'Washington', 'USA', 'Washington', 'National Mall', 'landmark', ['Lincoln Memorial']],
  ['Nashville Broadway', 'Nashville', 'USA', 'Nashville', 'Broadway', 'nightlife', ['Broadway Nashville']],
  ['Savannah Historic District', 'Savannah', 'USA', 'Savannah', 'Historic District', 'landmark', ['Savannah GA']],
  ['Charleston Rainbow Row', 'Charleston', 'USA', 'Charleston', 'Rainbow Row', 'landmark', ['Rainbow Row']],
  ['Denver Red Rocks', 'Denver', 'USA', 'Morrison', 'Red Rocks', 'landmark', ['Red Rocks Amphitheatre']],
  ['Banff Lake Moraine', 'Alberta', 'Canada', 'Banff', 'Moraine Lake', 'nature', ['Moraine Lake']],
  ['Quebec Old Quebec', 'Quebec', 'Canada', 'Quebec City', 'Old Quebec', 'landmark', ['Vieux Quebec']],
  ['Vancouver Stanley Park', 'Vancouver', 'Canada', 'Vancouver', 'Stanley Park', 'park', ['Stanley Park']],
  ['Montreal Old Port', 'Montreal', 'Canada', 'Montreal', 'Old Port', 'landmark', ['Vieux Port Montreal']],
  ['Chichen Itza El Castillo', 'Yucatan', 'Mexico', 'Chichen Itza', 'Archaeological Zone', 'landmark', ['El Castillo Chichen Itza']],
  ['Oaxaca Monte Alban', 'Oaxaca', 'Mexico', 'Oaxaca', 'Monte Alban', 'landmark', ['Monte Alban']],
  ['Copper Canyon', 'Chihuahua', 'Mexico', 'Creel', 'Copper Canyon', 'nature', ['Barranca del Cobre']],
  ['Rio Sugarloaf', 'Rio', 'Brazil', 'Rio de Janeiro', 'Urca', 'viewpoint', ['Sugarloaf Mountain']],
  ['Salvador Pelourinho', 'Bahia', 'Brazil', 'Salvador', 'Pelourinho', 'landmark', ['Pelourinho Salvador']],
  ['Florianopolis Beaches', 'Santa Catarina', 'Brazil', 'Florianopolis', 'Joaquina', 'beach', ['Florianopolis']],
  ['Buenos Aires Recoleta', 'Buenos Aires', 'Argentina', 'Buenos Aires', 'Recoleta', 'landmark', ['Recoleta Cemetery']],
  ['Mendoza Wine Region', 'Mendoza', 'Argentina', 'Mendoza', 'Maipu', 'landmark', ['Mendoza Wine']],
  ['Ushuaia End of World', 'Tierra del Fuego', 'Argentina', 'Ushuaia', 'Beagle Channel', 'landmark', ['Ushuaia']],
  ['Atacama Valle de la Luna', 'San Pedro', 'Chile', 'San Pedro de Atacama', 'Valle de la Luna', 'nature', ['Moon Valley Chile']],
  ['Easter Island Rano Raraku', 'Easter Island', 'Chile', 'Hanga Roa', 'Rano Raraku', 'landmark', ['Rano Raraku']],
  ['Galapagos Tortuga Bay', 'Galapagos', 'Ecuador', 'Puerto Ayora', 'Tortuga Bay', 'beach', ['Tortuga Bay Galapagos']],
  ['Quito Middle of the World', 'Quito', 'Ecuador', 'Quito', 'Mitad del Mundo', 'landmark', ['Mitad del Mundo']],
  ['Cartagena Castillo San Felipe', 'Cartagena', 'Colombia', 'Cartagena', 'San Felipe', 'landmark', ['San Felipe Castle']],
  ['Medellin Comuna 13', 'Medellin', 'Colombia', 'Medellin', 'Comuna 13', 'landmark', ['Comuna 13 Medellin']],
  ['Lake Titicaca Uros', 'Puno', 'Peru', 'Puno', 'Uros Islands', 'nature', ['Uros Floating Islands Peru']],
  ['Cusco Plaza de Armas', 'Cusco', 'Peru', 'Cusco', 'Plaza de Armas', 'landmark', ['Cusco Main Square']],
  ['Amazon Manaus Meeting Waters', 'Manaus', 'Brazil', 'Manaus', 'Meeting of Waters', 'nature', ['Encontro das Aguas']],
  ['Belize Great Blue Hole', 'Belize', 'Belize', 'Lighthouse Reef', 'Blue Hole', 'nature', ['Great Blue Hole']],
  ['Tikal Temple IV', 'Peten', 'Guatemala', 'Tikal', 'Temple IV', 'landmark', ['Tikal Temple 4']],
  ['Roatan West Bay', 'Roatan', 'Honduras', 'Roatan', 'West Bay', 'beach', ['West Bay Beach']],
  ['Antigua Guatemala', 'Sacatepequez', 'Guatemala', 'Antigua', 'Centro', 'landmark', ['Antigua Guatemala']],
  ['El Yunque Rainforest', 'Puerto Rico', 'USA', 'Rio Grande', 'El Yunque', 'nature', ['El Yunque NP']],
  ['St Lucia Pitons', 'St Lucia', 'St Lucia', 'Soufriere', 'Pitons', 'viewpoint', ['The Pitons']],
  ['Barbados Bridgetown', 'Barbados', 'Barbados', 'Bridgetown', 'Historic Bridgetown', 'landmark', ['Bridgetown UNESCO']],
  ['Great Ocean Road Twelve Apostles', 'Victoria', 'Australia', 'Port Campbell', 'Twelve Apostles', 'viewpoint', ['12 Apostles']],
  ['Blue Mountains Three Sisters', 'NSW', 'Australia', 'Katoomba', 'Three Sisters', 'viewpoint', ['Three Sisters Blue Mountains']],
  ['Fraser Island Lake McKenzie', 'Queensland', 'Australia', 'Fraser Island', 'Lake McKenzie', 'nature', ['Lake McKenzie']],
  ['Kakadu National Park', 'Northern Territory', 'Australia', 'Jabiru', 'Kakadu', 'nature', ['Kakadu NP']],
  ['Ayers Rock Sunset', 'Uluru', 'Australia', 'Yulara', 'Uluru', 'viewpoint', ['Uluru Sunset']],
  ['Tasmania Cradle Mountain', 'Tasmania', 'Australia', 'Cradle Mountain', 'Dove Lake', 'nature', ['Cradle Mountain']],
  ['Great Barrier Reef Whitsundays', 'Queensland', 'Australia', 'Whitsundays', 'Whitehaven', 'beach', ['Whitehaven Beach']],
  ['Rotorua Wai-O-Tapu', 'Rotorua', 'New Zealand', 'Rotorua', 'Wai-O-Tapu', 'nature', ['Wai-O-Tapu']],
  ['Abel Tasman Coast Track', 'Abel Tasman', 'New Zealand', 'Motueka', 'Coast Track', 'adventure', ['Abel Tasman NP']],
  ['Fiordland Milford Track', 'Fiordland', 'New Zealand', 'Te Anau', 'Milford', 'adventure', ['Milford Track']],
  ['Tongariro Alpine Crossing', 'Tongariro', 'New Zealand', 'National Park', 'Tongariro', 'adventure', ['Tongariro Crossing']],
  ['Bora Bora Mount Otemanu', 'Bora Bora', 'French Polynesia', 'Bora Bora', 'Otemanu', 'viewpoint', ['Mount Otemanu']],
  ['Fiji Yasawa Islands', 'Yasawa', 'Fiji', 'Yasawa Islands', 'Beach', 'beach', ['Yasawa Islands']],
  ['Samoa To Sua Ocean Trench', 'Upolu', 'Samoa', 'Upolu', 'To Sua', 'nature', ['To Sua Ocean Trench']],
  ['Tahiti Moorea Lagoon', 'Moorea', 'French Polynesia', 'Moorea', 'Lagoon', 'beach', ['Moorea Lagoon']],
  ['Hawaii Road to Hana', 'Maui', 'USA', 'Maui', 'Hana Highway', 'adventure', ['Road to Hana']],
  ['Waikiki Diamond Head', 'Honolulu', 'USA', 'Honolulu', 'Diamond Head', 'adventure', ['Diamond Head Crater']],
  ['Alaska Denali View', 'Alaska', 'USA', 'Denali', 'Park Road', 'viewpoint', ['Denali National Park']],
  ['Yellowstone Old Faithful', 'Wyoming', 'USA', 'Yellowstone', 'Upper Geyser', 'nature', ['Old Faithful']],
  ['Mount Rushmore', 'South Dakota', 'USA', 'Keystone', 'Mount Rushmore', 'landmark', ['Mount Rushmore NM']],
  ['Niagara Falls Canadian Side', 'Ontario', 'Canada', 'Niagara Falls', 'Horseshoe Falls', 'viewpoint', ['Horseshoe Falls']],
];
